### ISSUE TITLE
Needs more highly commented programs

### ISSUE THREAD

**Issue by vermiculus** [jsnider3/newbie_OCaml#1]

**Comment by jsnider3** [comment]
Any requests? I have two more I'm working on and plan to commit tomorrow.

**Comment by vermiculus** [comment]
Fibonacci is a classic – I find when I'm learning a language that going through the [Euler problems](https://projecteuler.net) is a good exercise.

**Comment by jsnider3** [comment]
Fibonacci achieved.

**Comment by jsnider3** [comment]
Marking as closed, now that I've wrapped up 498.

**Comment by vermiculus** [comment]
I dunno man. :wink:
